development:
  adapter: postgresql
  encoding: unicode
  database: web_app_with_self_destructing_messages
  pool: 2
  username: user_name
  password: user_password
#
# production:
#   adapter: postgresql
#   encoding: unicode
#   database: database_name
#   pool: 2
#   username: your_username
#   password: your_password
